### ISSUE TITLE
Linking failes on Mac OS 10.8

### ISSUE THREAD

**Issue by makzr** [edorfaus/TEMPered#11]
Hi, today I tried to build your lib on Mac OS Mountain Lion and got the following error. Maybe you can have a look at it.

markus@~/Downloads/TEMPered-master/build: make
Scanning dependencies of target tempered-shared
[  7%] Building C object libtempered/CMakeFiles/tempered-shared.dir/core.c.o
[ 14%] Building C object libtempered/CMakeFiles/tempered-shared.dir/temper_type.c.o
[ 21%] Building C object libtempered/CMakeFiles/tempered-shared.dir/type_hid/common.c.o
[ 28%] Building C object libtempered/CMakeFiles/tempered-shared.dir/type_hid/fm75.c.o
[ 35%] Building C object libtempered/CMakeFiles/tempered-shared.dir/type_hid/ntc.c.o
/Users/markus/Downloads/TEMPered-master/libtempered/type_hid/ntc.c:8: warning: unused parameter ‘group’
/Users/markus/Downloads/TEMPered-master/libtempered/type_hid/ntc.c:10: warning: unused parameter ‘group_data’
/Users/markus/Downloads/TEMPered-master/libtempered/type_hid/ntc.c:21: warning: unused parameter ‘tempC’
[ 42%] Building C object libtempered/CMakeFiles/tempered-shared.dir/type_hid/sht1x.c.o
Linking C shared library libtempered.dylib
Undefined symbols for architecture x86_64:
  "_hid_close", referenced from:
      _tempered_type_hid_close in common.c.o
     (maybe you meant: _tempered_type_hid_close)
  "_hid_enumerate", referenced from:
      _tempered_type_hid_enumerate in common.c.o
     (maybe you meant: _tempered_type_hid_enumerate)
  "_hid_error", referenced from:
      _tempered_type_hid_query in common.c.o
  "_hid_exit", referenced from:
      _tempered_type_hid_exit in common.c.o
     (maybe you meant: _tempered_type_hid_exit)
  "_hid_free_enumeration", referenced from:
      _tempered_type_hid_enumerate in common.c.o
  "_hid_init", referenced from:
      _tempered_type_hid_init in common.c.o
     (maybe you meant: _tempered_type_hid_init)
  "_hid_open_path", referenced from:
      _tempered_type_hid_open in common.c.o
  "_hid_read_timeout", referenced from:
      _tempered_type_hid_query in common.c.o
  "_hid_write", referenced from:
      _tempered_type_hid_query in common.c.o
ld: symbol(s) not found for architecture x86_64
collect2: ld returned 1 exit status
make[2]: **\* [libtempered/libtempered.0.dylib] Error 1
make[1]: **\* [libtempered/CMakeFiles/tempered-shared.dir/all] Error 2
make: **\* [all] Error 2

**Comment by jlebensold** [comment]
@makzr how did you fix this?

**Comment by vitaliJJ-source** [comment]
What was the fix?
