### ISSUE TITLE
Support for Fahrenheit 

### ISSUE THREAD

**Issue by dwilliss** [edorfaus/TEMPered#3]
I just purchased a TEMPer2HumiV1.1 and of course it didn't come with any support for Linux which is where I wanted to use it.  I found your solution via Google and it worked perfectly.  Thanks.

This isn't really an issue, but I couldn't find any other way to send you a message.

I wanted to show output in Fahrenheit (because we silly Americans still use Fahrenheit), so I modified utils/tempered.c to make it support a -F command line parameter.  In interest of Open Source, I'm submitting my change.  I don't know how to do this through git, so here's a context diff.  Hopefully you know how to read it or can figure it out.  I don't know if anybody still uses diff or if it's considered archaic these days.  I've been out of the Linux and C programming world for several years.  I didn't even know what github was.  I feel so ... old :-(

<pre>
*** tempered-orig.c     2012-05-19 17:20:49.916962407 -0500
--- tempered.c  2012-05-19 17:33:22.778961983 -0500
***************
*** 22,28 ****
  }

  /** Get and print the sensor values for a given device and sensor. */
! void print_device_sensor( tempered_device *device, int sensor )
  {
        float tempC, rel_hum;
        int type = tempered_get_sensor_type( device, sensor );
--- 22,28 ----
  }

  /** Get and print the sensor values for a given device and sensor. */
! void print_device_sensor( tempered_device *device, int sensor, int convert_to_fahrenheit )
  {
        float tempC, rel_hum;
        int type = tempered_get_sensor_type( device, sensor );
***************
*** 54,65 ****
                ( type & TEMPERED_SENSOR_TYPE_TEMPERATURE ) &&
                ( type & TEMPERED_SENSOR_TYPE_HUMIDITY )
        ) {
                printf(
!                       "%s %i: temperature %.2f°C"
                                ", relative humidity %.1f%%"
!                               ", dew point %.1f°C\n",
                        tempered_get_device_path( device ), sensor,
!                       tempC, rel_hum, get_dew_point( tempC, rel_hum )
                );
        }
        else if ( type & TEMPERED_SENSOR_TYPE_TEMPERATURE )
--- 54,73 ----
                ( type & TEMPERED_SENSOR_TYPE_TEMPERATURE ) &&
                ( type & TEMPERED_SENSOR_TYPE_HUMIDITY )
        ) {
+               char* temp_units = "C";
+               double dewpt = get_dew_point(tempC, rel_hum);
+
+               if (convert_to_fahrenheit) {
+                       temp_units = "F";
+                       tempC = (tempC * 9.0 / 5.0) + 32;
+                       dewpt = (dewpt * 9.0 / 5.0) + 32;
+                       }
                printf(
!                       "%s %i: temperature %.2f°%s"
                                ", relative humidity %.1f%%"
!                               ", dew point %.1f°%s\n",
                        tempered_get_device_path( device ), sensor,
!                       tempC, temp_units, rel_hum, dewpt, temp_units
                );
        }
        else if ( type & TEMPERED_SENSOR_TYPE_TEMPERATURE )
***************
*** 88,94 ****
  }

  /** Print the sensor values for a given device. */
! void print_device( struct tempered_device_list *dev )
  {
        char *error = NULL;
        tempered_device *device = tempered_open( dev, &error );
--- 96,102 ----
  }

  /** Print the sensor values for a given device. */
! void print_device( struct tempered_device_list *dev, int convert_to_fahrenheit )
  {
        char *error = NULL;
        tempered_device *device = tempered_open( dev, &error );
***************
*** 114,120 ****
                int sensor, sensors = tempered_get_sensor_count( device );
                for ( sensor = 0; sensor < sensors; sensor++ )
                {
!                       print_device_sensor( device, sensor );
                }
        }
        tempered_close( device );
--- 122,128 ----
                int sensor, sensors = tempered_get_sensor_count( device );
                for ( sensor = 0; sensor < sensors; sensor++ )
                {
!                       print_device_sensor( device, sensor, convert_to_fahrenheit );
                }
        }
        tempered_close( device );
***************
*** 123,128 ****
--- 131,137 ----
  int main( int argc, char **argv )
  {
        char *error = NULL;
+       int convert_to_fahrenheit = 0;
        if ( !tempered_init( &error ) )
        {
                fprintf( stderr, "Failed to initialize libtempered: %s\n", error );
***************
*** 138,143 ****
--- 147,168 ----
        }
        else
        {
+
+               if ( argc > 1 )
+           {
+                       for ( int i = 1; i < argc ; i++ )
+                       {
+                               if (!strcmp(argv[i], "-F"))
+                               {
+                                       convert_to_fahrenheit = true;
+                                       for (int j = i + 1 ; j < argc ; ++j)
+                                               argv[j-1] = argv[j];
+                                       --argc;
+                                       break;
+                               }
+                   }
+               }
+
                if ( argc > 1 )
                {
                        // We have parameters, so only print those devices that are given.
***************
*** 151,157 ****
                                        if ( strcmp( dev->path, argv[i] ) == 0 )
                                        {
                                                found = true;
!                                               print_device( dev );
                                                break;
                                        }
                                }
--- 176,182 ----
                                        if ( strcmp( dev->path, argv[i] ) == 0 )
                                        {
                                                found = true;
!                                               print_device( dev, convert_to_fahrenheit );
                                                break;
                                        }
                                }
***************
*** 170,176 ****
                        struct tempered_device_list *dev;
                        for ( dev = list ; dev != NULL ; dev = dev->next )
                        {
!                               print_device( dev );
                        }
                }
                tempered_free_device_list( list );
--- 195,201 ----
                        struct tempered_device_list *dev;
                        for ( dev = list ; dev != NULL ; dev = dev->next )
                        {
!                               print_device( dev, convert_to_fahrenheit );
                        }
                }
                tempered_free_device_list( list );

</pre>

**Comment by edorfaus** [comment]
> it worked perfectly. Thanks.

Good to hear; you're welcome! :)

> This isn't really an issue, but I couldn't find any other way to send you a message.

Oh, I don't know about that - feature requests are still issues IMO, even when they're nice enough to include patches that already implement them. :)

I'll take a closer look at this patch once I find some time to deal with it; thank you for sending it.

> Hopefully you know how to read it or can figure it out.

No worries - I've used diff far more (and longer) than I've used git and github. While I personally tend to prefer the syntax of unified diff, this is perfectly readable, and is supported by the patch command anyway, so works out just fine.

> I don't know if anybody still uses diff or if it's considered archaic these days.

While I'm not really in the loop much, I don't think diff is considered archaic - patches are still the simplest way of distributing changesets AFAIK, especially in text mediums like mailinglists.

> I didn't even know what github was. I feel so ... old :-(

Well, [some time has to be the first for everyone](http://xkcd.com/1053/)... It hasn't really been all that long since I first found out and started using it myself; I still catch myself trying to use it like subversion sometimes. :P

**Comment by edorfaus** [comment]
I've added support for displaying temperatures in Fahrenheit now, along with several other temperature scales.

I didn't end up using this patch, as I wanted a bit more flexibility (and to use a proper options parser), and the option ended up being different - but the functionality is now present.

Probably the easiest way to get Fahrenheit is now to use the option `-sf`, which is an abbreviated form of `--scale Fahrenheit` (since the scale name is matched case-insensitively).

For more information, including what other scales are available, use the `--help` option.
