### ISSUE TITLE
0c45:7401 with three sensors

### ISSUE THREAD

**Issue by meekstone** [edorfaus/TEMPered#7]
I got my hands on a 0c45:7401-device which has three sensors, one internal and two external. Below is the output of the commands given at https://github.com/edorfaus/TEMPered/wiki/TEMPer2.2

```
sudo ./hid-query -e
0002:0006:00 : 0c45:7401 interface 0 : RDing TEMPerNTC1.O
0002:0006:01 : 0c45:7401 interface 1 : RDing TEMPerNTC1.O

sudo ./hid-query 0002:0006:01 1 0x80 0x33 1
Device 0002:0006:01 : 0c45:7401 interface 1 : RDing TEMPerNTC1.O

Writing data (9 bytes):
         00 01 80 33   01 00 00 00   00

Response from device (8 bytes):
         80 06 1b c0   ff ff 1b 21

sudo ./hid-query 0002:0006:01 1 0x82 0x77 1
Device 0002:0006:01 : 0c45:7401 interface 1 : RDing TEMPerNTC1.O

Writing data (9 bytes):
         00 01 82 77   01 00 00 00   00

Response from device (8 bytes):
         82 03 00 00   00 ff 1b 21

sudo ./hid-query 0002:0006:01 1 0x86 0xff 1
Device 0002:0006:01 : 0c45:7401 interface 1 : RDing TEMPerNTC1.O

Writing data (9 bytes):
         00 01 86 ff   01 00 00 00   00

Response from device (8 bytes):
         54 45 4d 50   65 72 4e 54
Response from device (8 bytes):
         43 20 46 31   2e 30 4e 54
```

At the moment, tempered can not read any of the sensors:

```
sudo ./tempered
0002:0006:01: Could not open device: Unknown device subtype ID: 0x03
```

If you need any further information, I will try to provide it.

**Comment by edorfaus** [comment]
Hmm. I assume this is a recent TEMPerNTCII device, with both external sensors plugged in.

I'm guessing that the internal sensor is probably an FM75 type, and should if so not be hard to add support for.

The external ones, however, are a bit harder, as tempered doesn't have any code to read NTC sensors yet - and judging by the output of the commands above (one of the sensors reads ff ff), will probably require adjusting the gain on the fly, like some of the older NTC-based devices need (at least judging by the perl code I've seen for them).

To do that properly, I'll probably need some USB dumps of the windows program talking with it, along with the readings, preferably at several different temperatures... And might need some testing/experimentation before I get the code right. I've been intending to get one of those for myself so I can do that experimentation, but haven't actually bought one yet. If you're willing (and able) to do this part of the work for me, I can probably deal with the part that concerns turning that information into code, without having to get one myself first.

Meanwhile, to at least get readings from the internal sensor, you can edit libtempered/temper_type.c to make it recognize the device subtype - on line 90 where it says `.id = 1,` change it to say `.id = 3,` instead. If you want to try the external sensors too, you can instead change line 117 from 2 to 3 (but don't change both lines, or it'll act as if you only changed the first), and maybe the offsets on lines 141 and 142 (to 6 and 7) to try the second external sensor. Note that the external sensors probably won't give the correct temperatures with only these changes. (If they do, this may be simpler than I thought, but that doesn't seem likely at this point.)

**Comment by meekstone** [comment]
Changing only line 90 in libtempered/temper_type.c from `.id = 1,` to `.id = 3,` results in the internal sensor being read. The read temperature is consistent with what my thermometer reads.

Changing only line 117 in libtempered/temper_type.c from `.id = 2` to `.id = 3` results in two temperatures being read. The first reading seems to be the internal sensor, the second reading seems to be the first external sensor (labelled "A" on the device). I tested this by unplugging the external sensors and by raising their ambient temperature while connected. Readings seem to be pretty good.

Leaving line 117 in libtempered/temper_type.c from `.id = 2,` to `.id = 3,` and lines 141 and 142 to `.temperature_high_byte_offset = 6,` and `.temperature_low_byte_offset = 7` results in two temperatures being read. The first reading seems to be the internal sensor, the second reading seems to be the ~~first~~ second external sensor (labelled "B" on the device). I tested this as above. Readings once again seem to be pretty good.

When the code is modified to read one of the external sensors and this sensor is unplugged, then the reading is `-0.00 °C`.

Addendum: The device is indeed labelled as "TEMPerNTC II", further labelling reads "10K F3950 NTCsensor".

**Comment by edorfaus** [comment]
Really, now? That's interesting... Sounds like this device might be doing the NTC handling in hardware. Which makes the software's job a lot easier, if true.

I've added experimental support for all three sensors to the master branch now, based on what you said above. If you can try it, preferably with a wide range of temperatures*, and report back, that would be highly appreciated.

At the moment it assumes that both sensors are plugged in, but if one isn't, it should still work, just give that -0.00 value. (I can probably make it detect that, and not give any value at all, but didn't want to spend the effort if this doesn't work right anyway.)

*) I mean, like putting a sensor in the freezer for a while, take a reading, and putting it in (or near) something hot (like boiling water or a heater), and take a reading - just to check that it still gives sensible readings with extremes in temperature, not just when it's near room temperature.

**Comment by meekstone** [comment]
I did some testing with high and low temperatures.

High temperatures: I put the external sensors in boiling water. Let's call the external sensors "1" and "2", they can be connected to sockets "A" and "B". Sensor "1" gave a reading of 99°C when connected to socket "B" and a reading of 98°C when connected to socket "A". Sensor "2" gave a reading of 98°C when connected to socket "B" and a reading of 97°C when connected to socket "A". So there is a slight difference between sensors and between sockets. (Air pressure is around 1.01bar, so boiling water should indeed be at a temperature of 100°C.) I could not test the internal sensor because I have no idea how to raise its temperature to around 100°C, as the casing is not waterproof.

Low temperatures: I put the device (with both external sensors plugged in) into the fridge for 30 minutes. The fridge is set to -23°C, but I do not know the actual temperature. I do think that it is pretty close to the set temperature. I then took the device out of the fridge and about 30 seconds later (getting to my office, connecting the device), the internal sensor read -21.x°C. The external sensors read 0.0x°C and -3.x°C. I replugged the device, then the external sensors read about 5°C and the temperature read did not increase (but it did increase for the internal sensor). I unplugged the device, waited another 30 seconds, and replugged it. The external sensors now both read around 22°C, which was the ambient temperature.

Any idea how to raise the internal sensor's temperature? I will try to freeze the external sensors while they are submerged in water, so I will know for sure that their temperature will stay at "fridge temperature" after removing them from the fridge. As soon as I did that, which will not be before next week, I will report my findings.

**Comment by edorfaus** [comment]
That is quite interesting, thank you for doing it and writing about it.

Just based on what you've already told me, I think it's fairly safe to say that the NTC handling is done internally in this device (since the readings are sensible), and that the code to read it now seems to work. (Unless the unplugging and replugging you did was necessary for the readings to update?)

This also shows that the external sensors react to changes in temperature quite rapidly. The internal sensor does not, but that's pretty much to be expected, considering how much mass it is directly attached to (it's the same in the other devices as well).

As for getting the internal sensor up to 100°C, I had a few ideas - mostly consisting of wrapping it in something waterproof, e.g. a plastic bag or aluminum foil - but then I realized the plastic bits of the device (or bag) might not like temperatures that high anyway, and might start to melt, which would be bad. I know they say that the device can measure temperatures much higher than that, but I suspect they've simply taken the sensor's ratings without considering the casing etc. they've put it in. I could be wrong, of course, but I cannot in good conscience recommend trying it (and don't want to be held liable for doing so). I suppose you could try it if you don't mind destroying the device.

By the way, depending on your use case, you may want to calibrate your sensors before you use them for something real. Unfortunately, while the tempered program does support calibration, it currently does not support per-sensor calibration (because I haven't found any sensible way of specifying the calibration to that level via the command line parameters). Hence, your best bet for calibration would probably be to use sensor 1 in socket A and sensor 2 in socket B (since you then got a reading of 98°C from both), and then calibrate to an average of them or something like that. If you need it to be better than that, I guess you could do the calibration manually after getting the readings, or write your own specialized program that does the calibration per sensor. (Depending on your use case, you may want to write your own program anyway.)

**Comment by meekstone** [comment]
I froze one of the external sensors while the sensor was submerged in a small amount (about 50ml) of water. Fridge temperature was -23°C. After freezing, the external sensor read -21.9x°C, which is consistent with what the internal sensor read when I put the whole device into the fridge. Over a time of roughly half an hour, the temperature reading slowly increased to +1.0x°C, at which point the ice started melting (at its surface). I removed the sensors from the ice at a temperature of +2.0°C (it was still stuck in the ice at lower temperatures). It then took only about 40 seconds for the sensor to reach a reading of +22°C, which was ambient temperature.

It seems that the readings are quite sensible, and that the "misreadings" from my last test were probably correct readings, the external sensors just adjusted quite rapidly to the raised temperature.

Thanks for hinting towards calibration, I had already thought about that. But the primary use of the device will be monitoring/logging temperatures in an insectarium, which at the moment is not monitored constantly. There won't be anything important tied to it. So I'll probably just stick with what the sensors read, because 1 or 2 degrees off won't matter at all. I'll still see when there are extreme highs or lows and then act accordingly.

And of course a big thank you for getting support for this device so quickly. If you need further information, feel free to ask, I'll be sticking around this project.

**Comment by edorfaus** [comment]
Thank _you_, for all the information and for the help getting it to work! :) (That's one less device I'd have to buy just to get it to work... ;) )
